services:
  frontend:
    build: ./employee-list-fe
    volumes:
      - employee-list-fe-modules:/app/node_modules
      - ./employee-list-fe/:/app
    ports:
      - "5173:5173"
volumes:
  employee-list-fe-modules: